#!/usr/bin/perl
use threads;
use threads::shared;
use LWP::UserAgent;
use LWP::UserAgent::ProxyHopper;
use HTML::Strip;

print "Getting proxies ready.\n";
my $ua = LWP::UserAgent::ProxyHopper->new(agent => 'fox', timeout => 10);
my $proxylist_ua = LWP::UserAgent->new(agent => 'fox', timeout => 10);
my $proxylist_ret = $proxylist_ua->get('http://multiproxy.org/txt_anon/proxy.txt');
my $proxylist_content = "\"".$proxylist_ret->content;
my $cleanlist =~ s/\n/\",\"/g;
$ua->proxify_load(
    freeproxylists => 1,
    proxy4free     => 0,
    schemes        => 'http',
    retries        => 2,
#    extra_proxies  => (split(',',$cleanlist)),
    debug          => 1,
);

my $current_proxy = $ua->proxify_current;
print "Proxies are...$cleanlist\n";
print "Current proxy is ".$current_proxy."\n";
# Setup Proxy Hopper
# Setup URL
#$baseURL = "http://ink-n-iron.com/verify.php?em=1932&cid=";
my $baseURL = "http://ink-n-iron.com/verify.php?em=";

# Setup threadCount
our $threadCount :shared = 0;

#Setup zip array
our $location = 4000;
our $endlocation = 4025;
print "Starting while loop\n";
while( $location < $endlocation)
{
        if($threadCount < 5 )
        {
                $realURL = $baseURL."$location"."&cid=134";
                my $thr = threads->create(\&PullSite);
                $thr->detach;
                $threadCount++;
                $location++;
        }
}
print "Done!\n";
sub PullSite
{
                print "Entering PullSite\n";
                my $failedAttempt = 0;
pull:
                print "Getting $realURL\n";
                my $response = $ua->proxify_get($realURL);
                if($response->is_success )
                {
                        print "Getting was a success!\n";
                        my $content = $response->content;
                        my $hs = HTML::Strip->new();
                        my $cleanText = $hs->parse($content);
                        print $cleanText."\n";
                }
                else
                {
                        $failedAttempt++;
                        if($failedAttempt > 5)
                        {
                                print "Failed for the $failedAttempt time, moving on\n";
                        }
         
                }
}
